// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctgicjebjzgnegblpban.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Z2ljamVianpnbmVnYmxwYmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzY3ODksImV4cCI6MjA3MjIxMjc4OX0.Hsp-f3SP5tn36ikg7WlcKHaPARnyw-fLwfle17AyreM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});